name: Deploy document signature with rust
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install frontend dependancies
        run: pnpm install

      - name: Build project frontend
        run: pnpm run build

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "web/dist"

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
